# pip install streamlit
import streamlit as st 
import string
from spacy.lang.en.stop_words import STOP_WORDS as stopwords
import pickle
import spacy


st.title('AI Detector')
input_ = st.text_area(label='Enter you text')


# contractions = {
# "ain't": "am not",
# "aren't": "are not",
# "can't": "cannot",
# "can't've": "cannot have",
# "'cause": "because",
# "could've": "could have",
# "couldn't": "could not",
# "couldn't've": "could not have",
# "didn't": "did not",
# "doesn't": "does not",
# "don't": "do not",
# "hadn't": "had not",
# "hadn't've": "had not have",
# "hasn't": "has not",
# "haven't": "have not",
# "he'd": "he would",
# "he'd've": "he would have",
# "he'll": "he will",
# "he'll've": "he will have",
# "he's": "he is",
# "how'd": "how did",
# "how'd'y": "how do you",
# "how'll": "how will",
# "how's": "how does",
# "i'd": "i would",
# "i'd've": "i would have",
# "i'll": "i will",
# "i'll've": "i will have",
# "i'm": "i am",
# "i've": "i have",
# "isn't": "is not",
# "it'd": "it would",
# "it'd've": "it would have",
# "it'll": "it will",
# "it'll've": "it will have",
# "it's": "it is",
# "let's": "let us",
# "ma'am": "madam",
# "mayn't": "may not",
# "might've": "might have",
# "mightn't": "might not",
# "mightn't've": "might not have",
# "must've": "must have",
# "mustn't": "must not",
# "mustn't've": "must not have",
# "needn't": "need not",
# "needn't've": "need not have",
# "o'clock": "of the clock",
# "oughtn't": "ought not",
# "oughtn't've": "ought not have",
# "shan't": "shall not",
# "sha'n't": "shall not",
# "shan't've": "shall not have",
# "she'd": "she would",
# "she'd've": "she would have",
# "she'll": "she will",
# "she'll've": "she will have",
# "she's": "she is",
# "should've": "should have",
# "shouldn't": "should not",
# "shouldn't've": "should not have",
# "so've": "so have",
# "so's": "so is",
# "that'd": "that would",
# "that'd've": "that would have",
# "that's": "that is",
# "there'd": "there would",
# "there'd've": "there would have",
# "there's": "there is",
# "they'd": "they would",
# "they'd've": "they would have",
# "they'll": "they will",
# "they'll've": "they will have",
# "they're": "they are",
# "they've": "they have",
# "to've": "to have",
# "wasn't": "was not",
# " u ": " you ",
# " ur ": " your ",
# " n ": " and ",
# "won't": "would not",
# 'dis': 'this',
# 'bak': 'back',
# 'brng': 'bring',
# "won't":"would not",
# 'dis':'this',
# "bak":"back",
# "brng":'bring'
# }


def clean_text(text):
    tags = ['\n','\'']
    for tag in tags:
        text = text.replace(tag,'')

    # text = [x for x in text if x not in string.punctuation]
    text = ''.join(text)
  
    #streamli text = ''.join([t for t in text.split() if t not in stopwords])


    # if type(text) is str:
    #     for key in contractions:
    #         value = contractions[key]
    #         text = text.replace(key, value)
        
    return text


if input_:
    st.write(input_)
    input_ = clean_text(input_)
    clf_svm = pickle.load(open('clf.pkl','rb'))
    tfidf = pickle.load(open('tfidf.pkl','rb'))
    text = tfidf.transform([input_])
    result = clf_svm.predict(text)
    if(result):
        st.markdown("<h3>you text is generated by AI</h3>" ,  unsafe_allow_html = True)
    else:
        st.markdown("<h3>you text is generated by Human</h3>" , unsafe_allow_html = True)
